name: Build

on:
  # 有代码推送到 master 分支时触发
  push:
    branches: [master]
  # 允许手动在 Actions 页面触发此工作流
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      # 使用 actions/checkout@v4 拉取仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 设置 Java 环境
      # build.gradle 中指定 Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      # 赋予 Gradle Wrapper 执行权限
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 运行 Gradle 构建
      - name: Build with Gradle
        run: ./gradlew build

      # 上传构建产物
      # 将编译好的 Mod .jar 文件打包，方便下载
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          # 构建产物的名称
          name: BedrockCracker-Mod-JARs
          # 要上传的文件路径
          path: build/libs/
